name: Integration

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: [ stable, release ]
  pull_request:
    branches: [ stable, release ]
  workflow_dispatch:

jobs:
  integration_test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [ 3.8, '3.10' ]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .[profilers]
          pip install .[molecule_search]
          pip install .[requirements_adaptive]
          pip install pytest-cov
      - name: Test with pytest
        run: |
          pytest --cov=golem -s test/integration
